### ISSUE TITLE
For testing, allow the program to resubmit links

### ISSUE THREAD

**Issue by briandfoy** [dnmfarrell/Perly-Bot#13]
I hacked Reddit.pm to redefine methods in Reddit::Client to allow me to resubmit links. If we're debugging (in /r/perlybot), I want to try the same feed over and over again.

Reddit::Client doesn't support the full Reddit API.

**Comment by dnmfarrell** [comment]
Great idea. Reddit::Client ... is no longer working for me. I've switched over to Mojo::Snoo. I forked the dev version 0.14 which is the first version to be able to submit links. The version on cpan can't ...

**Comment by aggrolite** [comment]
@dnmfarrell I guess I forgot to make a CPAN release after adding support for link submission. Can't say I've tested it much, so do give me feedback on how it works. I can push it up to CPAN so it's all up to date.

**Comment by dnmfarrell** [comment]
@aggrolite sure thing, it seems link submission works fine so far. I haven't tested text submission.

**Comment by dnmfarrell** [comment]
I worked out the issue with Reddit::Client, so we can use either module (once Reddit::Client is patched) https://rt.cpan.org/Public/Bug/Display.html?id=110585

**Comment by dnmfarrell** [comment]
Ok this is easy - just set cache timeout to 1 second
