### ISSUE TITLE
Check links before submitting them

### ISSUE THREAD

**Issue by briandfoy** [dnmfarrell/Perly-Bot#24]
A particular blog we were tracking has gone private, but its feed is still public. All the links it advertises are protected, though. We should check links to ensure we get back something sensible. We should check links anyway to ensure that the actual content matches the description.

**Comment by briandfoy** [comment]
We can mark the feed as inactive in the feeds file (active: 0) or (inactive: 1), and I've patched up Feed.pm to have an is_active method. Still, we want to catch this before we know to configure it.

**Comment by briandfoy** [comment]
And, we already pull the links in root_url in ::Post.

**Comment by dnmfarrell** [comment]
The new content checks fetch the article, extract the text and then check the text for content. If the fetch fails, we skip the article
