### ISSUE TITLE
Feeds.t checks that the config has the same number of media targets

### ISSUE THREAD

**Issue by briandfoy** [dnmfarrell/Perly-Bot#3]
But, the perltricks.com config has one media target so it fails. I made it a TODO test.

**Comment by dnmfarrell** [comment]
Yeah ... I should fix this. Not sure why perltricks.com doesn't have one media target and one media object. It should only initialize as many objects as there are targets. Will look into this now...

**Comment by dnmfarrell** [comment]
Found the issue. It was caused because I was mocking the media objects and injecting both mocked objects into the feed object. `Perly::Bot` doesn't do this, hence the difference. Now fixed.
