### ISSUE TITLE
Create configuration defaults

### ISSUE THREAD

**Issue by briandfoy** [dnmfarrell/Perly-Bot#4]
We can reduce the size of the config file if most of the values are defaults. We should also be able to auto-detect the type of the resource, and configure it when we can't.

**Comment by briandfoy** [comment]
I've done something in 21989285c0af167f31fdc77a49afebd190cca44e in the log4perl branch of my repo (https://github.com/briandfoy/Perly-Bot/tree/log4perl)

**Comment by dnmfarrell** [comment]
Love it, I've merged these defaults in and pruned feeds.yml
