### ISSUE TITLE
Fix that nasty Unicode bug for blogs.perl.org

### ISSUE THREAD

**Issue by briandfoy** [dnmfarrell/Perly-Bot#8]
The blogs.perl.org feed doesn't transmit a content encoding, which was causing problems. It's the same problem as in http://ask.metafilter.com/26130/How-to-fix-an-Atom-feed

I changed to using Mojo::UserAgent because I think it's easier to handle Unicode. the ->body is octects and I can decode that.

But, XML::Atom::Client apparently has problems, which might simply be how it's documented. I tried XML::FeedPP and it handles the Unicode.

I also assumed that all Atom feeds will be UTF-8, which might be a problem later.

**Comment by dnmfarrell** [comment]
Aha! I switched over to XML::FeedPP in the branch unicode_fixes. If it looks good to you, I'll merge.

**Comment by dnmfarrell** [comment]
Ok I _think_ this is fixed ...
